AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  porteiro
  Sample SAM Template for porteiro

# Globals:
#   Function:
#     Timeout: 3

Resources:
  LigarPorteiro:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/porteiro.startEC2Instances
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 3

      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(21 23 ? * MON-FRI *) # [(?)=diaM (*)=mes (Mon-Fri)=dias (*)=ano]
            # Ajustar hora para ligar porteiro [(M H)soma hora atual +3]
            # Roda novamente o deploy: ✗ [sam deploy --profile bia-serverless]
      Policies:
        - Statement:
            - Sid: StartEC2
              Effect: Allow
              Action:
                - ec2:StartInstances
              Resource: '*'

  DesligarPorteiro:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/porteiro.stopEC2Instances
      Runtime: nodejs20.x
      Architectures:
        - x86_64

      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(22 23 ? * MON-FRI *) # [(?)=diaM (*)=mes (Mon-Fri)=dias (*)=ano]
            # Ajustar hora para descilar porteiro [(M H) soma hora atual +3]
            # Roda novamente o deploy: ✗ [sam deploy --profile bia-serverless]
      Policies:
        - Statement:
            - Sid: StopEC2
              Effect: Allow
              Action:
                - ec2:StopInstances
              Resource: '*'